procs:
  raft-node-1:
    shell: "nodemon ./src/server.js --port 8081"
  raft-node-2:
    shell: "nodemon ./src/server.js --port 8082"
  raft-node-3:
    shell: "nodemon ./src/server.js --port 8083"
  raft-node-4:
    shell: "nodemon ./src/server.js --port 8084"
  proxy:
    shell: "nodemon ./src/proxy.js"
  user-shell:
    cmd: ["zsh"]